# Generated by Django 5.0.6 on 2024-05-24 01:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clinic',
            options={'verbose_name': 'Clinic', 'verbose_name_plural': 'Clinics'},
        ),
    ]
